spin_manifest_version = 2

[application]
authors = ["anushkadeshpande <anushkaa5000@gmail.com>"]
description = ""
name = "hello-python"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "hello-python"

[component.hello-python]
source = "app.wasm"
[component.hello-python.build]
command = "componentize-py -w spin-http componentize app -o app.wasm"
watch = ["*.py", "requirements.txt"]
